GET http://localhost:3000/todos/?priority=HIGH

###
GET http://localhost:3000/todos/2

###

POST  http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 3,
  "todo": "learing event theme",
  "priority": "LOW",
  "status": "IN PROGRESS"
}


###
PUT   http://localhost:3000/todos/3
Content-Type: application/json

    {
      "priority": "Learing HTML"
    }
    
###
GET http://localhost:3000/todos/2

###
DELETE  http://localhost:3000/todos/2



